logging:
  level:
    org.springframework: error
    org.springframework.security: debug

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: <<databasename>>
      username: <<databaseuser>>
      password: <<databasepassword>>
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081


####### Mongock Properties ###########
mongock:
  migration-scan-package:
    - com.sample.springmongomigration.config.dbmigrations

